version: '2'
services:
    okulservis-app:
        image: okulservis
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://okulservis-postgresql:5432/okulservis
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=okulservis-elasticsearch:9300
        ports:
            - 8080:8080
    okulservis-postgresql:
        extends:
            file: postgresql.yml
            service: okulservis-postgresql
    okulservis-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: okulservis-elasticsearch
